//! Generated gateway bootstrap for sdkwork-inventory.
//! Regenerated by pnpm gateway:assembly:materialize.

use axum::Router;
use sdkwork_inventory_service_host::InventoryServiceHost;
use std::sync::Arc;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub async fn assemble_application_router(host: Arc<InventoryServiceHost>) -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_inventory_app_api::gateway_mount(host.clone()).await);
    router = router.merge(sdkwork_routes_inventory_backend_api::gateway_mount(host.clone()).await);
    ApplicationAssembly { router }
}
